<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ArticleSeeder extends Seeder
{
    public function run(): void
    {
        $articles = [
            [
                'slug'       => 'art-basel-brickell-popup',
                'title_en'   => 'Art Basel Satellite Show Opens in Brickell Warehouse District',
                'title_es'   => 'Exposición Satélite de Art Basel Abre en el Distrito de Almacenes de Brickell',
                'summary_en' => 'Thirty emerging Latin American artists transform a riverfront warehouse into an immersive gallery through March.',
                'summary_es' => 'Treinta artistas latinoamericanos emergentes transforman un almacén frente al río en una galería inmersiva hasta marzo.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'events',
                'author'     => 'Javier Morales',
                'date'       => '2026-02-17',
                'featured'   => false,
                'priority'   => 8,
            ],
            [
                'slug'       => 'bayfront-transit-hub',
                'title_en'   => 'Bayfront Transit Hub Breaks Ground',
                'title_es'   => 'Inicia la Construcción del Centro de Tránsito Bayfront',
                'summary_en' => 'The long-awaited multimodal hub promises faster commutes and new retail along the waterfront.',
                'summary_es' => 'El esperado centro multimodal promete viajes más rápidos y nuevos comercios frente al mar.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'news',
                'author'     => 'Sofia Delgado',
                'date'       => '2026-02-03',
                'featured'   => true,
                'priority'   => 10,
            ],
            [
                'slug'       => 'bilingual-school-expansion',
                'title_en'   => "Brickell's First Bilingual Charter School Announces Expansion",
                'title_es'   => 'La Primera Escuela Charter Bilingüe de Brickell Anuncia Expansión',
                'summary_en' => 'Enrollment doubles as the K-8 academy adds a STEM wing and dual-language immersion track.',
                'summary_es' => 'La matrícula se duplica mientras la academia K-8 añade un ala STEM y un programa de inmersión bilingüe.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'news',
                'author'     => 'Natalie Chen',
                'date'       => '2026-02-06',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-art-festival',
                'title_en'   => 'Brickell Art Festival Returns with International Artists',
                'title_es'   => 'Regresa el Festival de Arte de Brickell con Artistas Internacionales',
                'summary_en' => 'Annual cultural event showcases sculptures, paintings, and live performances.',
                'summary_es' => 'Evento cultural anual presenta esculturas, pinturas y presentaciones en vivo.',
                'body_en'    => '<p>Over 200 artists from 30 countries will display their work along SW 8th Street. Free workshops and bilingual tours available.</p>',
                'body_es'    => '<p>Más de 200 artistas de 30 países exhibirán sus obras a lo largo de SW 8th Street. Talleres gratuitos y recorridos bilingües disponibles.</p>',
                'image'      => 'https://images.unsplash.com/photo-1536924940846-6b05b89e27aa?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Sofia Rodriguez',
                'date'       => '2026-02-06',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-beach-access',
                'title_en'   => 'New Beach Access Route from Brickell',
                'title_es'   => 'Nueva Ruta de Acceso a la Playa desde Brickell',
                'summary_en' => 'Dedicated bike lane and shuttle service connect Brickell to South Beach.',
                'summary_es' => 'Carril bici dedicado y servicio de transporte conectan Brickell con South Beach.',
                'body_en'    => '<p>Service runs every 15 minutes during peak hours with stops at major hotels and attractions.</p>',
                'body_es'    => '<p>El servicio corre cada 15 minutos en horas pico con paradas en los principales hoteles y atracciones.</p>',
                'image'      => 'https://images.unsplash.com/photo-1507525428034-b723a9ce6890?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Diego Fernandez',
                'date'       => '2026-02-14',
                'featured'   => false,
                'priority'   => 5,
            ],
            [
                'slug'       => 'brickell-bridge-closure',
                'title_en'   => 'Brickell Avenue Bridge Closes for Emergency Repairs',
                'title_es'   => 'El Puente de Brickell Avenue Cierra por Reparaciones de Emergencia',
                'summary_en' => 'Commuters face two-week detour as engineers replace corroded support beams on the drawbridge.',
                'summary_es' => 'Los viajeros enfrentan un desvío de dos semanas mientras los ingenieros reemplazan vigas corroídas del puente levadizo.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'news',
                'author'     => 'Camila Torres',
                'date'       => '2026-02-16',
                'featured'   => true,
                'priority'   => 10,
            ],
            [
                'slug'       => 'brickell-civic-plaza',
                'title_en'   => 'Brickell Civic Plaza Nears Completion',
                'title_es'   => 'El Brickell Civic Plaza Está Cerca de su Finalización',
                'summary_en' => 'City offices, art spaces, and a public rooftop park open this summer.',
                'summary_es' => 'Oficinas municipales, espacios artísticos y un parque en la azotea abrirán este verano.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1444419988133-046ed4e5ffd6?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'news',
                'author'     => 'Camila Torres',
                'date'       => '2026-01-22',
                'featured'   => false,
                'priority'   => 4,
            ],
            [
                'slug'       => 'brickell-coffee-scene',
                'title_en'   => "Inside Brickell's Exploding Specialty Coffee Scene",
                'title_es'   => 'Dentro de la Explosiva Escena de Café de Especialidad en Brickell',
                'summary_en' => "From Colombian micro-lots to Cuban cortadito flights, five new cafés are redefining the neighborhood's morning ritual.",
                'summary_es' => 'Desde micro-lotes colombianos hasta vuelos de cortadito cubano, cinco nuevos cafés redefinen el ritual matutino del barrio.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Lucia Navarro',
                'date'       => '2026-02-11',
                'featured'   => false,
                'priority'   => 7,
            ],
            [
                'slug'       => 'brickell-coworking-boom',
                'title_en'   => 'Co-Working Spaces Double in Brickell as Remote Work Surges',
                'title_es'   => 'Los Espacios de Co-Working se Duplican en Brickell ante el Auge del Trabajo Remoto',
                'summary_en' => 'Three new flexible office hubs open within blocks of each other, targeting Latin American freelancers and digital nomads.',
                'summary_es' => 'Tres nuevos centros de oficinas flexibles abren a pocas cuadras entre sí, dirigidos a freelancers y nómadas digitales latinoamericanos.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'business',
                'author'     => 'Daniel Ruiz',
                'date'       => '2026-02-10',
                'featured'   => false,
                'priority'   => 7,
            ],
            [
                'slug'       => 'brickell-crypto-hub',
                'title_en'   => "Brickell Becomes Florida's Unofficial Crypto Capital",
                'title_es'   => 'Brickell se Convierte en la Capital Cripto No Oficial de Florida',
                'summary_en' => 'Blockchain firms lease 200,000 sq ft of office space as the district cements its fintech reputation.',
                'summary_es' => 'Firmas blockchain alquilan 200,000 pies cuadrados de oficinas mientras el distrito consolida su reputación fintech.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'business',
                'author'     => 'Daniel Ruiz',
                'date'       => '2026-02-16',
                'featured'   => false,
                'priority'   => 8,
            ],
            [
                'slug'       => 'brickell-farmers-market',
                'title_en'   => 'New Sunday Farmers Market Launches Under the Metrorail',
                'title_es'   => 'Nuevo Mercado Dominical de Productores Debuta Bajo el Metrorail',
                'summary_en' => 'Local growers and artisan food makers set up weekly stalls with organic produce and ready-to-eat bites.',
                'summary_es' => 'Productores locales y artesanos gastronómicos instalan puestos semanales con productos orgánicos y bocados listos para comer.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'events',
                'author'     => 'Priya Patel',
                'date'       => '2026-02-05',
                'featured'   => false,
                'priority'   => 5,
            ],
            [
                'slug'       => 'brickell-finance-summit',
                'title_en'   => 'Brickell Finance Summit Announces Global Speakers',
                'title_es'   => 'La Cumbre de Finanzas de Brickell Anuncia Ponentes Mundiales',
                'summary_en' => 'Leading economists and fintech innovators will gather at the annual summit this March.',
                'summary_es' => 'Economistas líderes e innovadores fintech se reunirán en la cumbre anual este marzo.',
                'body_en'    => '<p>The Brickell Finance Summit returns with a focus on sustainable finance and digital transformation. Speakers include Nobel laureate economists and CEOs of major Latin American banks.</p>',
                'body_es'    => '<p>La Cumbre de Finanzas de Brickell regresa con un enfoque en finanzas sostenibles y transformación digital. Los ponentes incluyen economistas ganadores del Premio Nobel y CEOs de los principales bancos latinoamericanos.</p>',
                'image'      => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'business',
                'author'     => 'Carlos Martinez',
                'date'       => '2026-02-10',
                'featured'   => true,
                'priority'   => 9,
            ],
            [
                'slug'       => 'brickell-flooding-response',
                'title_en'   => 'Mayor Declares Emergency After Brickell Flash Flooding',
                'title_es'   => 'La Alcaldesa Declara Emergencia Tras Inundaciones Repentinas en Brickell',
                'summary_en' => 'Record rainfall overwhelms storm drains along Brickell Avenue; shelters open at Mary Brickell Village.',
                'summary_es' => 'Lluvias récord desbordan los drenajes de Brickell Avenue; se abren refugios en Mary Brickell Village.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'headline-news',
                'author'     => 'Camila Torres',
                'date'       => '2026-02-20',
                'featured'   => true,
                'priority'   => 10,
            ],
            [
                'slug'       => 'brickell-food-festival',
                'title_en'   => 'Brickell Food Festival Draws 50,000 Visitors',
                'title_es'   => 'Festival de Comida de Brickell Atrae 50,000 Visitantes',
                'summary_en' => 'Annual culinary event features international cuisines and celebrity chef demonstrations.',
                'summary_es' => 'Evento culinario anual presenta cocinas internacionales y demostraciones de chefs famosos.',
                'body_en'    => '<p>Over 100 food vendors participate with live music and cooking competitions throughout the weekend.</p>',
                'body_es'    => '<p>Más de 100 vendedores de comida participan con música en vivo y concursos de cocina durante todo el fin de semana.</p>',
                'image'      => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'events',
                'author'     => 'Marco Rodriguez',
                'date'       => '2026-02-16',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-hidden-speakeasies',
                'title_en'   => "Four Hidden Speakeasies You Didn't Know Existed in Brickell",
                'title_es'   => 'Cuatro Speakeasies Ocultos que No Sabías que Existían en Brickell',
                'summary_en' => 'Behind unmarked doors and inside parking garages, these secret bars serve craft cocktails with a Miami twist.',
                'summary_es' => 'Detrás de puertas sin marcar y dentro de estacionamientos, estos bares secretos sirven cócteles artesanales con toque miamense.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Javier Morales',
                'date'       => '2026-02-08',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-hotel-tower',
                'title_en'   => 'Six-Star Hotel Tower Planned for Brickell',
                'title_es'   => 'Planeada Torre de Hotel de Seis Estrellas en Brickell',
                'summary_en' => 'Luxury hotel chain announces 40-story tower with spa and conference center.',
                'summary_es' => 'Cadena de hoteles de lujo anuncia torre de 40 pisos con spa y centro de conferencias.',
                'body_en'    => '<p>The $300 million project includes 300 rooms, multiple restaurants, and rooftop infinity pool.</p>',
                'body_es'    => '<p>El proyecto de $300 millones incluye 300 habitaciones, múltiples restaurantes y piscina infinita en la azotea.</p>',
                'image'      => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'real-estate',
                'author'     => 'Victoria Chen',
                'date'       => '2026-02-15',
                'featured'   => true,
                'priority'   => 8,
            ],
            [
                'slug'       => 'brickell-key-park-redesign',
                'title_en'   => 'Brickell Key Park Gets $40M Redesign With Mangrove Trail',
                'title_es'   => 'El Parque de Brickell Key Recibe Rediseño de $40M con Sendero de Manglares',
                'summary_en' => 'The island park will feature a boardwalk through restored mangroves, a children\'s splash pad, and a floating stage.',
                'summary_es' => 'El parque de la isla contará con un paseo por manglares restaurados, un área de juegos acuáticos y un escenario flotante.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'real-estate',
                'author'     => 'Sofia Delgado',
                'date'       => '2026-02-08',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-luxury-shopping',
                'title_en'   => 'Luxury Shopping Complex Opens in Brickell',
                'title_es'   => 'Abre Complejo de Compras de Lujo en Brickell',
                'summary_en' => 'High-end retail center features designer boutiques and fine dining.',
                'summary_es' => 'Centro comercial de alta gama presenta boutiques de diseñadores y gastronomía fina.',
                'body_en'    => '<p>The $200 million development includes valet parking, personal shopping services, and rooftop gardens.</p>',
                'body_es'    => '<p>El desarrollo de $200 millones incluye estacionamiento con valet, servicios de compras personalizados y jardines en la azotea.</p>',
                'image'      => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Isabella Martinez',
                'date'       => '2026-02-12',
                'featured'   => false,
                'priority'   => 5,
            ],
            [
                'slug'       => 'brickell-marathon',
                'title_en'   => 'Annual Brickell Marathon Draws Record Participants',
                'title_es'   => 'Maratón Anual de Brickell Atrae Récord de Participantes',
                'summary_en' => 'Over 15,000 runners from 40 countries compete in scenic urban race.',
                'summary_es' => 'Más de 15,000 corredores de 40 países compiten en carrera urbana panorámica.',
                'body_en'    => '<p>Race route passes through Brickell Avenue with live music and food vendors along the course.</p>',
                'body_es'    => '<p>La ruta de la carrera pasa por Brickell Avenue con música en vivo y vendedores de comida a lo largo del recorrido.</p>',
                'image'      => 'https://images.unsplash.com/photo-1541252260730-0412e8e2108e?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'events',
                'author'     => 'Miguel Torres',
                'date'       => '2026-02-07',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-marina-expansion',
                'title_en'   => 'Brickell Marina Expansion Wins Final Approval',
                'title_es'   => 'Expansión de la Marina de Brickell Obtiene Aprobación Final',
                'summary_en' => 'Updated plans add public docks, coral-safe lighting, and a maritime innovation lab.',
                'summary_es' => 'Los planes actualizados incluyen muelles públicos, iluminación segura para los corales y un laboratorio de innovación marítima.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'real-estate',
                'author'     => 'Elena Brooks',
                'date'       => '2026-01-30',
                'featured'   => false,
                'priority'   => 5,
            ],
            [
                'slug'       => 'brickell-mega-tower-approved',
                'title_en'   => 'City Council Green-Lights 80-Story Mega Tower on Brickell Bay',
                'title_es'   => 'El Concejo Municipal Aprueba Megatorre de 80 Pisos en Brickell Bay',
                'summary_en' => 'The $2.1 billion mixed-use project will become Miami\'s tallest building, sparking debate over density and views.',
                'summary_es' => 'El proyecto de uso mixto de $2.1 mil millones será el edificio más alto de Miami, generando debate sobre densidad y vistas.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'headline-news',
                'author'     => 'Marcus Lee',
                'date'       => '2026-02-19',
                'featured'   => true,
                'priority'   => 10,
            ],
            [
                'slug'       => 'brickell-metro-extension',
                'title_en'   => 'Metro Extension to Brickell Approved',
                'title_es'   => 'Aprobada Extensión del Metro a Brickell',
                'summary_en' => 'New underground line will connect Brickell to Miami International Airport.',
                'summary_es' => 'Nueva línea subterránea conectará Brickell con el Aeropuerto Internacional de Miami.',
                'body_en'    => '<p>Construction begins in June with completion expected by 2029. The project includes three new stations in Brickell.</p>',
                'body_es'    => '<p>La construcción comienza en junio con finalización prevista para 2029. El proyecto incluye tres nuevas estaciones en Brickell.</p>',
                'image'      => 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'news',
                'author'     => 'Thomas Anderson',
                'date'       => '2026-02-11',
                'featured'   => true,
                'priority'   => 10,
            ],
            [
                'slug'       => 'brickell-neighborhood-watch',
                'title_en'   => 'Brickell Neighborhood Watch App Reaches 5,000 Users',
                'title_es'   => 'La App de Vigilancia Vecinal de Brickell Alcanza 5,000 Usuarios',
                'summary_en' => 'The community safety platform reports a 30% drop in package theft since its launch six months ago.',
                'summary_es' => 'La plataforma de seguridad comunitaria reporta una caída del 30% en robo de paquetes desde su lanzamiento hace seis meses.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'home',
                'author'     => 'Natalie Chen',
                'date'       => '2026-02-10',
                'featured'   => false,
                'priority'   => 5,
            ],
            [
                'slug'       => 'brickell-night-market',
                'title_en'   => 'Brickell Night Market Returns With Art & DJs',
                'title_es'   => 'Regresa el Brickell Night Market con Arte y DJs',
                'summary_en' => 'Friday pop-up along South Miami Avenue blends artisan vendors, vinyl, and late-night bites.',
                'summary_es' => 'Un pop-up los viernes en South Miami Avenue mezcla artesanos, vinilos y bocados nocturnos.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'events',
                'author'     => 'Lucia Navarro',
                'date'       => '2026-02-02',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-park-renovation',
                'title_en'   => 'Brickell Park Renovation Begins',
                'title_es'   => 'Comienza la Renovación del Parque Brickell',
                'summary_en' => '$12 million upgrade adds new playground, dog park, and fitness equipment.',
                'summary_es' => 'Mejora de $12 millones agrega nuevo patio de juegos, parque para perros y equipo de ejercicio.',
                'body_en'    => '<p>Community input sessions scheduled throughout February. Project expected to complete by summer 2026.</p>',
                'body_es'    => '<p>Sesiones de participación comunitaria programadas durante febrero. El proyecto finaliza en verano de 2026.</p>',
                'image'      => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Laura Mendez',
                'date'       => '2026-02-03',
                'featured'   => false,
                'priority'   => 5,
            ],
            [
                'slug'       => 'brickell-pet-friendly',
                'title_en'   => "Brickell Ranked Miami's Most Pet-Friendly Neighborhood",
                'title_es'   => 'Brickell Clasificado como el Barrio Más Pet-Friendly de Miami',
                'summary_en' => 'New dog parks, vet clinics, and pet-welcome policies at local restaurants earn the district top marks.',
                'summary_es' => 'Nuevos parques para perros, clínicas veterinarias y políticas pet-friendly en restaurantes le dan al distrito las mejores calificaciones.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Priya Patel',
                'date'       => '2026-02-15',
                'featured'   => false,
                'priority'   => 5,
            ],
            [
                'slug'       => 'brickell-power-outage',
                'title_en'   => 'Massive Power Outage Leaves 12,000 Brickell Residents in the Dark',
                'title_es'   => 'Apagón Masivo Deja a 12,000 Residentes de Brickell a Oscuras',
                'summary_en' => 'FPL crews race to restore service after a transformer failure knocks out electricity across 30 blocks.',
                'summary_es' => 'Las cuadrillas de FPL trabajan para restaurar el servicio tras una falla de transformador que afecta 30 cuadras.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'headline-news',
                'author'     => 'Sofia Delgado',
                'date'       => '2026-02-17',
                'featured'   => true,
                'priority'   => 9,
            ],
            [
                'slug'       => 'brickell-recycling-program',
                'title_en'   => 'Brickell Launches Building-by-Building Recycling Challenge',
                'title_es'   => 'Brickell Lanza Desafío de Reciclaje Edificio por Edificio',
                'summary_en' => 'Residents compete for prizes as the district aims to double its recycling rate by summer.',
                'summary_es' => 'Los residentes compiten por premios mientras el distrito busca duplicar su tasa de reciclaje para el verano.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'home',
                'author'     => 'Priya Patel',
                'date'       => '2026-02-13',
                'featured'   => false,
                'priority'   => 5,
            ],
            [
                'slug'       => 'brickell-restaurant-row',
                'title_en'   => "Five Celebrity Chefs Set to Open on Brickell's New Restaurant Row",
                'title_es'   => 'Cinco Chefs Famosos Abrirán en la Nueva Zona Gastronómica de Brickell',
                'summary_en' => 'A wave of high-profile openings transforms South Miami Avenue into a dining destination rivaling Wynwood.',
                'summary_es' => 'Una ola de aperturas de alto perfil transforma South Miami Avenue en un destino gastronómico que rivaliza con Wynwood.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'business',
                'author'     => 'Lucia Navarro',
                'date'       => '2026-02-11',
                'featured'   => false,
                'priority'   => 7,
            ],
            [
                'slug'       => 'brickell-restaurant-week',
                'title_en'   => 'Brickell Restaurant Week Returns with Celebrity Chefs',
                'title_es'   => 'Regresa la Semana de Restaurantes de Brickell con Chefs Famosos',
                'summary_en' => 'Ten-day culinary celebration features prix-fixe menus at 50+ venues.',
                'summary_es' => 'Celebración culinaria de diez días presenta menús de precio fijo en más de 50 locales.',
                'body_en'    => '<p>Participating restaurants range from casual cafes to Michelin-starred establishments.</p>',
                'body_es'    => '<p>Los restaurantes participantes van desde cafés informales hasta establecimientos con estrella Michelin.</p>',
                'image'      => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Patricia Lopez',
                'date'       => '2026-02-09',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-rooftop-pools',
                'title_en'   => 'The Best Rooftop Pools in Brickell Open to Non-Residents',
                'title_es'   => 'Las Mejores Piscinas en Azoteas de Brickell Abiertas al Público',
                'summary_en' => 'Day passes, cabana rentals, and bottomless brunch deals at five towers welcoming visitors this spring.',
                'summary_es' => 'Pases de día, alquiler de cabañas y brunch ilimitado en cinco torres que reciben visitantes esta primavera.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Lucia Navarro',
                'date'       => '2026-02-14',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-run-5k',
                'title_en'   => 'Brickell Run 5K Returns With Record 3,000 Runners',
                'title_es'   => 'El Brickell Run 5K Regresa con Récord de 3,000 Corredores',
                'summary_en' => 'The annual charity race benefits local youth programs and shuts down Brickell Avenue for a Sunday morning celebration.',
                'summary_es' => 'La carrera benéfica anual beneficia programas juveniles locales y cierra Brickell Avenue para una celebración dominical.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'events',
                'author'     => 'Natalie Chen',
                'date'       => '2026-02-09',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-salsa-festival',
                'title_en'   => 'Brickell Salsa Festival Brings 20 Live Bands to Bayfront',
                'title_es'   => 'El Festival de Salsa de Brickell Trae 20 Bandas en Vivo a Bayfront',
                'summary_en' => "Two days of dance workshops, food trucks, and concerts celebrate Miami's Latin music roots.",
                'summary_es' => 'Dos días de talleres de baile, food trucks y conciertos celebran las raíces de la música latina de Miami.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'events',
                'author'     => 'Javier Morales',
                'date'       => '2026-02-13',
                'featured'   => false,
                'priority'   => 7,
            ],
            [
                'slug'       => 'brickell-scooter-regulations',
                'title_en'   => 'City Approves New E-Scooter Regulations for Brickell',
                'title_es'   => 'La Ciudad Aprueba Nuevas Regulaciones de Scooters Eléctricos para Brickell',
                'summary_en' => 'Speed caps, designated parking zones, and helmet requirements take effect next month.',
                'summary_es' => 'Límites de velocidad, zonas de estacionamiento designadas y requisitos de casco entran en vigor el próximo mes.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'news',
                'author'     => 'Daniel Ruiz',
                'date'       => '2026-02-07',
                'featured'   => false,
                'priority'   => 5,
            ],
            [
                'slug'       => 'brickell-startup-accelerator',
                'title_en'   => 'Startup Accelerator Launches in Brickell',
                'title_es'   => 'Lanza Aceleradora de Startups en Brickell',
                'summary_en' => 'New program offers $100k investment and mentorship to early-stage companies.',
                'summary_es' => 'Nuevo programa ofrece inversión de $100k y mentoría a empresas en etapa temprana.',
                'body_en'    => '<p>Applications open next month with focus on fintech, healthtech, and sustainable technologies.</p>',
                'body_es'    => '<p>Las solicitudes abren el próximo mes con enfoque en fintech, healthtech y tecnologías sostenibles.</p>',
                'image'      => 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'business',
                'author'     => 'Jennifer Wu',
                'date'       => '2026-02-13',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-tech-job-fair',
                'title_en'   => 'Brickell Tech Job Fair Adds AI Pavilion',
                'title_es'   => 'La Feria de Empleo Tech de Brickell Añade Pabellón de IA',
                'summary_en' => 'Regional employers court bilingual talent with on-site interviews and portfolio reviews.',
                'summary_es' => 'Empleadores regionales buscan talento bilingüe con entrevistas en el lugar y revisión de portafolios.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'events',
                'author'     => 'Natalie Chen',
                'date'       => '2026-01-27',
                'featured'   => false,
                'priority'   => 5,
            ],
            [
                'slug'       => 'brickell-traffic-update',
                'title_en'   => 'Weekly Traffic Update: I-95 Ramp Closures Affect Brickell Commuters',
                'title_es'   => 'Actualización de Tráfico Semanal: Cierres de Rampas de I-95 Afectan a Viajeros de Brickell',
                'summary_en' => 'Detour routes and alternate transit options for the next two weeks of highway construction.',
                'summary_es' => 'Rutas de desvío y opciones de transporte alternativo durante las próximas dos semanas de construcción.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'home',
                'author'     => 'Sofia Delgado',
                'date'       => '2026-02-18',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'brickell-water-main-break',
                'title_en'   => 'Water Main Break Disrupts Service on SE 1st Street',
                'title_es'   => 'Rotura de Tubería Principal Interrumpe Servicio en SE 1st Street',
                'summary_en' => 'Crews work overnight to restore supply to four residential towers and a dozen storefronts.',
                'summary_es' => 'Las cuadrillas trabajan toda la noche para restaurar el suministro a cuatro torres residenciales y una docena de locales.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'news',
                'author'     => 'Camila Torres',
                'date'       => '2026-02-19',
                'featured'   => false,
                'priority'   => 7,
            ],
            [
                'slug'       => 'brickell-weekend-highlights',
                'title_en'   => 'This Weekend in Brickell: Markets, Music & Murals',
                'title_es'   => 'Este Fin de Semana en Brickell: Mercados, Música y Murales',
                'summary_en' => 'Your curated guide to the best things happening around the neighborhood this Saturday and Sunday.',
                'summary_es' => 'Tu guía seleccionada de las mejores actividades del barrio este sábado y domingo.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'home',
                'author'     => 'Lucia Navarro',
                'date'       => '2026-02-20',
                'featured'   => false,
                'priority'   => 8,
            ],
            [
                'slug'       => 'latam-investment-summit',
                'title_en'   => 'LatAm Investment Summit Draws Record Attendance to Brickell',
                'title_es'   => 'La Cumbre de Inversión LatAm Atrae Asistencia Récord a Brickell',
                'summary_en' => 'Over 2,000 investors from 14 countries gather to discuss real estate, crypto, and cross-border commerce.',
                'summary_es' => 'Más de 2,000 inversionistas de 14 países se reúnen para discutir bienes raíces, cripto y comercio transfronterizo.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'business',
                'author'     => 'Elena Brooks',
                'date'       => '2026-02-14',
                'featured'   => false,
                'priority'   => 8,
            ],
            [
                'slug'       => 'luxury-tower-brickell',
                'title_en'   => 'Luxury Tower Breaks Ground in Brickell',
                'title_es'   => 'Torre de Lujo Inicia Construcción en Brickell',
                'summary_en' => '55-story residential building will feature sky pool and private helipad.',
                'summary_es' => 'Edificio residencial de 55 pisos contará con piscina en el cielo y helipuerto privado.',
                'body_en'    => "<p>Brickell's skyline transforms again with the announcement of The Azure Tower. Units start at \$2.5 million with penthouses exceeding \$15 million.</p>",
                'body_es'    => '<p>El horizonte de Brickell se transforma nuevamente con el anuncio de The Azure Tower. Las unidades comienzan en $2.5 millones y los penthouse superan los $15 millones.</p>',
                'image'      => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'real-estate',
                'author'     => 'Roberto Silva',
                'date'       => '2026-02-05',
                'featured'   => true,
                'priority'   => 7,
            ],
            [
                'slug'       => 'metro-mover-upgrade',
                'title_en'   => 'Metromover Gets $120M Upgrade With New Brickell Stations',
                'title_es'   => 'El Metromover Recibe Mejora de $120M con Nuevas Estaciones en Brickell',
                'summary_en' => 'Two additional stops and air-conditioned cars aim to cut commute times by 15 minutes during rush hour.',
                'summary_es' => 'Dos paradas adicionales y vagones con aire acondicionado buscan reducir 15 minutos el viaje en hora pico.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'news',
                'author'     => 'Sofia Delgado',
                'date'       => '2026-02-18',
                'featured'   => false,
                'priority'   => 9,
            ],
            [
                'slug'       => 'miami-fintech-accelerator',
                'title_en'   => 'Miami Fintech Accelerator Selects Brickell Startups',
                'title_es'   => 'Aceleradora Fintech de Miami Selecciona Startups de Brickell',
                'summary_en' => 'Eight early-stage founders land seed capital and bilingual mentorship this spring.',
                'summary_es' => 'Ocho fundadores en etapa temprana obtienen capital semilla y mentoría bilingüe esta primavera.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'business',
                'author'     => 'Daniel Ruiz',
                'date'       => '2026-01-26',
                'featured'   => false,
                'priority'   => 7,
            ],
            [
                'slug'       => 'river-district-condos',
                'title_en'   => 'River District Pre-Sales Sell Out in 48 Hours',
                'title_es'   => 'Las Preventas del River District se Agotan en 48 Horas',
                'summary_en' => 'Luxury waterfront condos starting at $1.2M attract buyers from New York, Buenos Aires, and São Paulo.',
                'summary_es' => 'Condominios de lujo frente al agua desde $1.2M atraen compradores de Nueva York, Buenos Aires y São Paulo.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'real-estate',
                'author'     => 'Marcus Lee',
                'date'       => '2026-02-12',
                'featured'   => false,
                'priority'   => 8,
            ],
            [
                'slug'       => 'riverwalk-expansion',
                'title_en'   => 'Miami Riverwalk Expansion Reaches Brickell',
                'title_es'   => 'La Expansión del Miami Riverwalk Llega a Brickell',
                'summary_en' => 'New pedestrian bridge and waterfront promenade will connect downtown to Brickell.',
                'summary_es' => 'Nuevo puente peatonal y paseo marítimo conectarán el centro con Brickell.',
                'body_en'    => '<p>The $85 million project includes green spaces, art installations, and kayak launches. Construction begins next month with completion expected in 2027.</p>',
                'body_es'    => '<p>El proyecto de $85 millones incluye espacios verdes, instalaciones artísticas y lanzaderos de kayak. La construcción comienza el próximo mes con finalización prevista en 2027.</p>',
                'image'      => 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1f?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'news',
                'author'     => 'Maria Gonzalez',
                'date'       => '2026-02-08',
                'featured'   => true,
                'priority'   => 8,
            ],
            [
                'slug'       => 'skyline-garden-tower',
                'title_en'   => 'Skyline Garden Tower Tops Out',
                'title_es'   => 'La Torre Skyline Garden Alcanza su Altura Máxima',
                'summary_en' => 'The 62-story residential project unveils rooftop amenities centered on urban agriculture.',
                'summary_es' => 'El proyecto residencial de 62 pisos presenta amenidades en la azotea enfocadas en agricultura urbana.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'real-estate',
                'author'     => 'Marcus Lee',
                'date'       => '2026-01-28',
                'featured'   => true,
                'priority'   => 9,
            ],
            [
                'slug'       => 'sunset-rooftop-dining',
                'title_en'   => 'Sunset Rooftop Dining Guide',
                'title_es'   => 'Guía de Comidas al Atardecer en las Azoteas',
                'summary_en' => 'Five new terraces pair chef tastings with skyline views.',
                'summary_es' => 'Cinco nuevas terrazas combinan degustaciones de chefs con vistas al horizonte.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Javier Morales',
                'date'       => '2026-02-01',
                'featured'   => false,
                'priority'   => 6,
            ],
            [
                'slug'       => 'tech-hub-brickell',
                'title_en'   => 'Major Tech Company Opens Hub in Brickell',
                'title_es'   => 'Gran Empresa Tecnológica Abre Centro en Brickell',
                'summary_en' => 'Silicon Valley giant creates 500 new jobs with state-of-the-art office space.',
                'summary_es' => 'Gigante de Silicon Valley crea 500 nuevos empleos con oficinas de última generación.',
                'body_en'    => '<p>The expansion includes AI research facilities and a startup incubator program focused on Latin American markets.</p>',
                'body_es'    => '<p>La expansión incluye instalaciones de investigación en IA y un programa de incubadora de startups enfocado en mercados latinoamericanos.</p>',
                'image'      => 'https://images.unsplash.com/photo-1497366214047-f4e2f9dc4a01?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'business',
                'author'     => 'David Kim',
                'date'       => '2026-02-04',
                'featured'   => false,
                'priority'   => 7,
            ],
            [
                'slug'       => 'waterfront-wellness-series',
                'title_en'   => 'Waterfront Wellness Series Announces Spring Lineup',
                'title_es'   => 'Serie de Bienestar en la Costa Anuncia Programación de Primavera',
                'summary_en' => 'Free sunrise yoga and mindful paddling clinics return every Saturday.',
                'summary_es' => 'Regresan las clases gratuitas de yoga al amanecer y clínicas de remo consciente cada sábado.',
                'body_en'    => null,
                'body_es'    => null,
                'image'      => 'https://images.unsplash.com/photo-1484981137413-84e607ccfcfc?auto=format&fit=crop&w=1600&q=80',
                'category'   => 'lifestyle',
                'author'     => 'Priya Patel',
                'date'       => '2026-02-04',
                'featured'   => false,
                'priority'   => 5,
            ],
        ];

        // Cache category IDs by slug to avoid N+1 queries
        $categoryIds = Category::pluck('id', 'slug');

        foreach ($articles as $data) {
            $categorySlug = $data['category'];
            $categoryId = $categoryIds[$categorySlug] ?? null;

            if (!$categoryId) {
                $this->command->warn("Category '{$categorySlug}' not found, skipping article '{$data['slug']}'");
                continue;
            }

            Article::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'title_en'    => $data['title_en'],
                    'title_es'    => $data['title_es'],
                    'summary_en'  => $data['summary_en'],
                    'summary_es'  => $data['summary_es'],
                    'body_en'     => $data['body_en'],
                    'body_es'     => $data['body_es'],
                    'image'       => $data['image'],
                    'category_id' => $categoryId,
                    'author'      => $data['author'],
                    'date'        => $data['date'],
                    'featured'    => $data['featured'],
                    'priority'    => $data['priority'],
                ]
            );
        }

        $this->command->info('Seeded ' . count($articles) . ' articles.');
    }
}
